### ISSUE TITLE
Error when make run_tests on ubuntu14

### ISSUE THREAD

**Issue by sisihi** [GoogleCloudPlatform/cpp-docs-samples#24]
Hi,
I am working on ubuntu 14.04.

I've compiled the latest grpc(with libc-ares-dev (1.13.0)) and protobuf.

but when make run_tests:

> ar: creating googleapis.ar
g++ transcribe.o parse_arguments.o googleapis.ar -L/usr/local/lib `pkg-config --libs grpc++ grpc` -Wl,--no-as-needed -lgrpc++_reflection -Wl,--as-needed -lprotobuf -lpthread -ldl -o transcribe
/usr/local/lib/libgrpc.so: undefined reference to `ares_set_servers_ports'
collect2: error: ld returned 1 exit status
make: *** [transcribe] Error 1

Seems like I've picked the wrong version for the c-ares, so how can I fix the error? Thanks.

Besides, the libc-ares-dev (1.11.0) will fail the make of grpc, so I manually make the 1.13.0 for grpc.

**Comment by coryan** [comment]
Thank you for the bug report.  We need your help to reproduce the problem (and then fix it!)

What exactly do you mean by "latest grpc"?
Did you compile and install the master branch?  Or v1.6.x?  Or v1.4.x?

Can you include the command you used to download grpc? 
If you used `git` to clone the grpc repository, can you include the output from `git status` and/or `git rev-parse HEAD`?

**Comment by coryan** [comment]
I have tested the build on Ubuntu 14.04 against the v1.4.x version of grpc, it works without problem.  You can find the shell script and Dockerfile I used here:

https://github.com/coryan/cpp-docs-samples/tree/fix-issue-24/speech/api/ci

I *think* the main difference is that we normally compile grpc against the c-ares submodule.  That is, grpc is **not** compiled against `libc-ares-dev`, it is compiled against the submodule in `third_party/cares`.  The commands to compile and install `grpc` are:

```console
git clone https://github.com/grpc/grpc.git
cd grpc
git checkout v1.4.x
git submodule update --init
make -j 2
make install
cd third_party/protobuf
make install
```

**Comment by sisihi** [comment]
I suppose ur point is to install the `protobuf` from the `grpc/third_party/protobuf/` instead of [https://github.com/google/protobuf/blob/3.1.x/src/README.md](url)

So, I've tried the method which is similar to

> WORKDIR /var/tmp/build-grpc
RUN (git clone https://github.com/grpc/grpc.git && \
    cd grpc && git checkout v1.4.x && git submodule update --init && \
    make -j 2 && make install && \
    cd third_party/protobuf && make install)

But there is error when 

> cd third_party/protobuf
make install

which give me:

> /grpc/third_party/protobuf$ -> make install
make: *** No rule to make target `install'.  Stop.


I've checkout the v1.4.x grpc already, did I missed something?Thanks

**Comment by coryan** [comment]
> I suppose ur point is to install the protobuf from the grpc/third_party/protobuf/ instead of 
> https://github.com/google/protobuf/blob/3.1.x/src/README.md

I did not make that point explicitly, but yes, you want to install the dependencies from `grpc/third_party` instead of trying to find matching versions from somewhere else.

> So, I've tried the method which is similar to

You say "similar", do you mean to say you used exactly those commands, or something else?  If something else, would you mind showing the exact commands that you used?
